### ISSUE TITLE
Build error with latest Slicer-5.1

### ISSUE THREAD

**Issue by lassoan** [openigtlink/SlicerOpenIGTLink#124]
Build error: https://slicer.cdash.org/viewBuildError.php?buildid=2828793

Similar to https://github.com/IGSIO/SlicerIGSIO/issues/24

@Sunderlandkyl could you look into it?

**Comment by jamesobutler** [comment]
I've built with latest updates and it appears to be resolved with latest Slicer:
https://github.com/openigtlink/SlicerOpenIGTLink/commit/0df19d0cb97a3aeb5ec9bea5d7848b99f1a6f23c
https://github.com/IGSIO/IGSIO/commit/44f68876d956ea51b076b4ccea3f7850a42a4d03
https://github.com/IGSIO/OpenIGTLinkIO/commit/207f5cd7c7234d83cf53e674de8753243221d825

**Comment by Sunderlandkyl** [comment]
Fixed on nightly dashboard build: https://slicer.cdash.org/build/2831641
