### ISSUE TITLE
How to use python code to call the slicer plug-in: OpenIGTLink in the external compiler pycharm?

### ISSUE THREAD

**Issue by ningw-git** [openigtlink/SlicerOpenIGTLink#133]
I am trying to do secondary development based on slicer, and I have made a new software using Python. Now I have a problem: how to install the slicer plug-in: OpenIGTLink in my software? Or how to use Python code in the compiler pycharm to call this plug-in? Please help me, as a beginner, I really need help.

**Comment by Sunderlandkyl** [comment]
To connect to Plus/OpenIGTLink within Slicer with Python, you need to create and activate a vtkMRMLIGTLConnectorNode.
```python
connectorNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLIGTLConnectorNode")
connectorNode.SetServerHostname("localhost")
connectorNode.SetServerPort(18944)
connectorNode.Start()
```

**Comment by ningw-git** [comment]
Thank you very much for your answer. According to the content you provided, I successfully connected to the plus server.
Now I want to call another plug-in Fiducial Registration Wizard: I want to realize the registration function. How can I realize this registration function in my python code? It's really troublesome for you.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openigtlink/SlicerOpenIGTLink"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openigtlink/SlicerOpenIGTLink] How to use python code to call the slicer plug-in: OpenIGTLink in the external compiler pycharm? (Issue #133)





 
To connect to Plus/OpenIGTLink within Slicer with Python, you need to create and activate a vtkMRMLIGTLConnectorNode.
 connectorNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLIGTLConnectorNode") connectorNode.SetServerHostname("localhost") connectorNode.SetServerPort(18944) connectorNode.Start()

**Comment by ningw-git** [comment]
![image](https://github.com/user-attachments/assets/e84fedc8-4788-47fa-b69d-6e9eb2a8bc72)
This is the plugin. I want to use its function to realize the registration function. Please help.

> To connect to Plus/OpenIGTLink within Slicer with Python, you need to create and activate a vtkMRMLIGTLConnectorNode.
> 
> ```python
> connectorNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLIGTLConnectorNode")
> connectorNode.SetServerHostname("localhost")
> connectorNode.SetServerPort(18944)
> connectorNode.Start()
> ```

**Comment by Sunderlandkyl** [comment]
You'll need to add a [vtkMRMLFiducialRegistrationWizardNode](https://github.com/SlicerIGT/SlicerIGT/blob/master/FiducialRegistrationWizard/MRML/vtkMRMLFiducialRegistrationWizardNode.h), add the from/to markups nodes, and then call ```slicer.modules.fiducialregistrationwizard.logic().UpdateCalibration(wizardNode)```.

**Comment by Sunderlandkyl** [comment]
Not a complete example, but something like:
```
wizardNode.SetAndObserveFromFiducialListNodeId(fromMarkupsNode.GetID())
wizardNode.SetAndObserveToFiducialListNodeId(toMarkupsNode.GetID())
wizardNode.SetOutputTransformNodeId(outputTransformNode.GetID())
slicer.modules.fiducialregistrationwizard.logic().UpdateCalibration(wizardNode)
```

**Comment by ningw-git** [comment]
Thank you very much for your answer.
Thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openigtlink/SlicerOpenIGTLink"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月19日(星期一) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openigtlink/SlicerOpenIGTLink] How to use python code to call the slicer plug-in: OpenIGTLink in the external compiler pycharm? (Issue #133)





 
Not a complete example, but something like:
 wizardNode.SetAndObserveFromFiducialListNodeId(fromMarkupsNode.GetID()) wizardNode.SetAndObserveToFiducialListNodeId(toMarkupsNode.GetID()) wizardNode.SetOutputTransformNodeId(outputTransformNode.GetID()) slicer.modules.fiducialregistrationwizard.logic().UpdateCalibration(wizardNode)

**Comment by ningw-git** [comment]
I'm here to bother you again. I've encountered a new problem. First, I installed the OpenIGT plug-in in slicer, and then created a new plug-in script myself. According to your code, I can call this plug-in. However, I now want to add this function to the software developed by our team, so how can I install the OpenIGT plug-in on both sides of my software? My software is a secondary development based on slicer. I'm really sorry to bother you.

> Not a complete example, but something like:
> 
> ```
> wizardNode.SetAndObserveFromFiducialListNodeId(fromMarkupsNode.GetID())
> wizardNode.SetAndObserveToFiducialListNodeId(toMarkupsNode.GetID())
> wizardNode.SetOutputTransformNodeId(outputTransformNode.GetID())
> slicer.modules.fiducialregistrationwizard.logic().UpdateCalibration(wizardNode)
> ```

**Comment by ningw-git** [comment]
![image](https://github.com/user-attachments/assets/4ac602c1-ca13-4285-9fa2-8de5dee59775)
this is our project construct,thanks again!

**Comment by Sunderlandkyl** [comment]
You are trying to communicate between Slicer and your software?
You would likely need to add an OpenIGTLink implementation to communicate between them.
I'm not sure I can provide a recommendation without knowing more about your software.

**Comment by ningw-git** [comment]
Thank you for your reply. I want to know whether I can package and install the slicer plug-in into my software. Since I did not develop the software, I do not know the specific logic. I only know that the software is developed based on slicer. How can I package and install the plug-in in slicer? Please help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openigtlink/SlicerOpenIGTLink"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月20日(星期二) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openigtlink/SlicerOpenIGTLink] How to use python code to call the slicer plug-in: OpenIGTLink in the external compiler pycharm? (Issue #133)





 
You are trying to communicate between Slicer and your software?
 You would likely need to add an OpenIGTLink implementation to communicate between them.
 I'm not sure I can provide a recommendation without knowing more about your software.

**Comment by lassoan** [comment]
> I want to know whether I can package and install the slicer plug-in into my software.

Yes, you can.

>  I only know that the software is developed based on slicer.

You may ask the person who develops that software to ask questions from us.

> How can I package and install the plug-in in slicer

You can use SlicerCAT - https://github.com/KitwareMedical/SlicerCAT
