### ISSUE TITLE
Moving OpenIGTLinkRemote and PlusRemote into this extension

### ISSUE THREAD

**Issue by lassoan** [openigtlink/SlicerOpenIGTLink#24]
Since OpenIGTLinkIF is in a separate extension now, we should move OpenIGTLinkRemote and PlusRemote extensions here. They belong to each other - a change in SlicerOpenIGTLinkIF is likely to impact OpenIGTLinkRemote and PlusRemote as well, and this would remove the hard dependency of SlicerIGT extension on SlicerOpenIGTLink extension. See also https://github.com/SlicerIGT/SlicerIGT/issues/173.

@leochan2009 Do you agree? If yes, then we'll send a pull request that contains these two modules.

**Comment by leochan2009** [comment]
It make sense to move the OpenIGTLinkRemote to SlicerOpenIGTLink.
Regarding the PlusRemote module, i think we need to rename it to make it not Plus-related.
Please send the pull request, i will review it,
Thanks,
Longquan

**Comment by Sunderlandkyl** [comment]
I added the migration of PlusRemote and OpenIGTLinkRemote to #19.

Any suggestions on what to rename PlusRemote?

**Comment by lassoan** [comment]
Unlike OpenIGTLinkRemote, PlusRemote is not a general remote control module, but it is developed specifically to work with Plus. I don't think it should be renamed.

**Comment by leochan2009** [comment]
En, this is just a personal opinion. Previously I had the inclination of keeping the library to itself, and only include the modules that are generalized,  and move the PlusRemote to another extension.
After talking with Junichi,  we are fine with the expanding of SlicerOpenIGTLink extension.
probably in the future, we could even include MatlabBridge into SlicerOpenIGTLink
I will review the change and merge the commit soon
