### ISSUE TITLE
Slicer crashes when streaming webcam to Slicer from Plus

### ISSUE THREAD

**Issue by Sunderlandkyl** [openigtlink/SlicerOpenIGTLink#25]
I've found that streaming from a webcam to Slicer using Plus will cause Slicer to crash when using the latest nightly (4.9.0-2018-04-16). It doesn't seem to happen with other types of images. Plus continues to run without error.

It seems to happen reliably, although the crash doesn't always happen right away. I've replicated the crash using both the color and greyscale MMF config files (https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_MmfVideoCapture.xml and https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_Server_MmfColorVideoCapture.xml)

When I debugged SlicerOpenIGTLink using Visual Studio, it crashes here:
https://github.com/openigtlink/OpenIGTLink/blob/54ea5a0ce55b8280f363e24f74eb3c1bd40ed5a1/Source/igtlMessageBase.cxx#L760

There are no remarkable messages in the log that I can see: ([Slicer_27152_20180417_153715.log](https://github.com/openigtlink/SlicerOpenIGTLink/files/1921314/Slicer_27152_20180417_153715.log))

I'll look into this some more, but I'm not really that familiar with base OpenIGTLink.
Any suggestions as to possible causes would be appreciated.

**Comment by Sunderlandkyl** [comment]
I should clarify that this is on Windows. I'll try to test on Linux and MacOS.

**Comment by leochan2009** [comment]
Hi Kyle,
Thanks for reporting! i will take a look ASAP

**Comment by leochan2009** [comment]
Tried on the nightly build on April 1st, no crash happens, now will check on the latest nightly build

**Comment by Sunderlandkyl** [comment]
It's quite strange. I can still replicate the issue on Windows, but not on Mac anymore.

**Comment by leochan2009** [comment]
I reproduced the same bug in my Windows machine too.  Currently working on it

**Comment by leochan2009** [comment]
Bug found, let's check the nightly build tomorrow!

**Comment by Sunderlandkyl** [comment]
Thanks for taking a look at this Longquan!

**Comment by leochan2009** [comment]
Fixed
