### ISSUE TITLE
Build tree not convenient for Slicer module list

### ISSUE THREAD

**Issue by adamrankin** [openigtlink/SlicerOpenIGTLink#50]
Windows 10
Visual Studio 2015 x64

After doing a build, I manually copy a number of files to the `lib/Slicer-4.9/...` folder so that it can find all the necessary DLLs. It would be nice if they were all build to a single folder.

Currently:
1. <build>/bin/$(Configuration)/ contains DLLs such as `igtlioConverter.dll`, `OpenIGTLink.dll`, etc...
1. <build>/lib/$(Configuration)/ contains pyds such as `igtlioConverterPython.pyd`, etc...
1. <build>/inner-build/lib/Slicer-4.9/qt-loadable-modules/Release/ contains Slicer module dlls as expected

Ideally, if all files were built to the 3. location, then in Slicer you'd only have to add one folder to the module list and not manually copy files

**Comment by leochan2009** [comment]
Yes, this issue probably relates to #42 .
You can avoid copying files by using the additional setting files #18 
Slicer.exe --launcher-additional-settings c:\D\SlicerOpenIGTLink-win64rel\inner-build\AdditionalLauncherSettings.ini
We could change super-build output directory of OpenIGTLink and OpenIGTLinkIO to be the same as Slicer Module dlls.  but I am not sure if Slicer requires the third party libraries to be in different locations from the module dlls location.
