### ISSUE TITLE
Cannot close main windows after visiting PlusRemote

### ISSUE THREAD

**Issue by ungi** [openigtlink/SlicerOpenIGTLink#52]
Tested on Windows, version 2018-08-01

To reproduce:
- Select Plus Remote module
- Try to close Slicer by closing the main window with the X button in the top right corner.
The X button remains disabled for me, even when selecting other modules.

**Comment by leochan2009** [comment]
@Sunderlandkyl

**Comment by Sunderlandkyl** [comment]
Should be fixed by #54.

**Comment by jamesobutler** [comment]
Tested and observed no issues closing Slicer after opening the PlusRemote module.
