### ISSUE TITLE
Missing modules in Linux, Slicer nightly build

### ISSUE THREAD

**Issue by tavaughan** [openigtlink/SlicerOpenIGTLink#58]
Steps I did in Ubuntu 18.04:
1. Download latest nightly
2. Unzip Slicer
3. Go to extension manager
4. Install OpenIGTLink
5. Restart Slicer
6. Look for PLUSRemote, OpenIGTLinkIF, or other modules

**Comment by leochan2009** [comment]
The .so files (OpenIGTLink and OpenIGTLinkIO) are located in the wrong location. copy the files to the location as shown in the screenshot will solve the problem. Will dig into the problem.
![image](https://user-images.githubusercontent.com/10211992/45844281-f21d1d00-bcef-11e8-9e23-9dbe066ae6ab.png)

**Comment by MaXZon3** [comment]
> The .so files (OpenIGTLink and OpenIGTLinkIO) are located in the wrong location. copy the files to the location as shown in the screenshot will solve the problem. Will dig into the problem.

I had the same issue and this quick fix works. :sweat_smile:

**Comment by Sunderlandkyl** [comment]
Fixed by 9e0f3f3
