### ISSUE TITLE
[Feature Request] Sending fiducial points/Markup points via OpenIGTLinkIF

### ISSUE THREAD

**Issue by chaicl95** [openigtlink/SlicerOpenIGTLink#67]
I would like to request a new feature where the module can send and receive fiducial points/markup points via OpenIGTLinkIF. I found that the OpenIGTLink Library has the capability to send point with 3D coordinates as PointMessage. 
For my knowledge, this feature is not implemented currently. It would be nice to have this feature since my current project required me to send a group of 3D coordinate points into Slicer as markup points to perform landmark registration.

**Comment by leochan2009** [comment]
Hi,

You can use transformation message to send 3D coordinates points. In slicer there will be vtkmrmltransformationnode created. You can then apply the node to fiducial markups

**Comment by chaicl95** [comment]
I see. Is there maximum number of transformation message that I can send in one go because I need to send quite a number of points (around 80)?

**Comment by leochan2009** [comment]
you only send one message at one time. But you could send them in a for loop. You will need to align each transformation node with each fiducial in slicer. Each transformation node in slicer is created automatically when a transformation message is received. The node will be updated automatically with upcoming message. When you send the message, make sure you have the name setup from the sender side. The name is used for node creation and update.

**Comment by chaicl95** [comment]
Thanks for the info. I'll try it.

**Comment by leochan2009** [comment]
https://github.com/SlicerIGT/SlicerIGT/tree/master/FiducialRegistrationWizard

Here is some examples for fiducial registration, hope it helps!

**Comment by adamrankin** [comment]
You could also look into [TDATA](https://github.com/openigtlink/OpenIGTLink/blob/master/Documents/Protocol/trackingdata.md) messages, as they can send arbitrary number of transforms in a single message.

**Comment by lassoan** [comment]
The described workaround is acceptable for some use cases, but at some point we'll have to implement transfer of fiducial list as POINTS message.

Shouldn't we keep this ticket open as a feature request?

**Comment by tokjun** [comment]
I agree with @lassoan . I've just realized that [ROS-IGTL-Bridge](https://github.com/openigtlink/ROS-IGTL-Bridge) is not fully working with the new OpenIGTLinkIF because of this limitation.

**Comment by ChiaraTe** [comment]
HI, why is this option possible in slicer 4.8.1 and not in slicer 4.10.1?

**Comment by angad15** [comment]
Same problem as @tokjun. ROS-IGTL-Bridge is not fully working.

**Comment by adamrankin** [comment]
After acquiring an Intel RealSense camera, I realize this is needed to send point clouds to Slicer. I'll start working on it.

**Comment by lassoan** [comment]
We send the RealSense point cloud as depth image and convert to polydata in Slicer using this module: https://github.com/PerkLab/DepthImageToPointCloud. Sending the point cloud in a polydata message would be more general, but it is more efficient this way.

This ticket is about fiducials, which is typically just a few ten points, may be up to a few thousand, and they are converted to markup fiducials in Slicer.

**Comment by lassoan** [comment]
This is implemented now.
