### ISSUE TITLE
PlusRemote: "Add timestamp" checkbox unused

### ISSUE THREAD

**Issue by ageorgou** [openigtlink/SlicerOpenIGTLink#76]
In the PlusRemote widget, the section related to live reconstruction has a checkbox labelled "Add timestamp to filename", which doesn't appear to do anything: the resulting filename does not have a timestamp.

Looking in the source, I can see why: `vtkSlicerPlusRemoteLogic::StartLiveVolumeReconstruction` indeed does not look at the state of that checkbox, and instead directly uses the value from the corresponding textbox.

https://github.com/openigtlink/SlicerOpenIGTLink/blob/debddd8d9b1df44e010031ba5dcaca24c678de8a/PlusRemote/Logic/vtkSlicerPlusRemoteLogic.cxx#L574

This is in contrast to `vtkSlicerPlusRemoteLogic::StartScoutScan` and `vtkSlicerPlusRemoteLogic::StartRecording`, which will append the timestamp if the corresponding box is checked.

If this is not intentional, I'm happy to submit a PR changing it so that it works like the others!

**Comment by Sunderlandkyl** [comment]
It's not intentional. If you would like to submit a PR fixing this issue, it would be much appreciated!
