### ISSUE TITLE
Builds on Windows are not copying DLLs correctly

### ISSUE THREAD

**Issue by markasselin** [openigtlink/SlicerOpenIGTLink#86]
DLLs from <SlicerOpenIGTLink-Build-Dir>/bin/Release are not copied to the inner build, so the OpenIGTLink module is not loaded correctly when Slicer launches in a custom build.

**Comment by adamrankin** [comment]
Wait, is this fixed? This is a very annoying issue!

**Comment by markasselin** [comment]
Slicer also loads dlls from /bin/Release, so this is not actually an error. It is inconvenient during development though

**Comment by adamrankin** [comment]
I'd say this is something worth fixing!

**Comment by Sunderlandkyl** [comment]
I think that the real problem is the fact that multiple --launcher-additional-settings cannot be supplied to the same Slicer.

AFAIK, their current location is the standard for extensions with third party libraries.
